class Solution:
    def reverseWords(self, s: str) -> str:
        # Split on spaces to preserve word boundaries, then reverse the word order.
        # Empty strings may appear in the split result when there are multiple spaces.
        reversedWords = s.split(" ")[::-1]
        reversedWordsString = ""
        for word in reversedWords:
            # Skip empty segments generated by consecutive spaces.
            if word != "":
                reversedWordsString += f" {word}"
        # The string was built with a leading space, so strip it off.
        return reversedWordsString[1:]